Algoritmo "sem nome"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 26/07/2023
Var
// Seção de Declarações das variáveis 

valor: inteiro

Inicio


   escreva("Digite um valor: ")
   leia(valor)

   se valor >= 0 entao
      escreva("O valor é positivo.")
   senao
      escreva("O valor é negativo.")
   fimse

Fimalgoritmo